# Generated by Django 4.1.6 on 2023-02-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='temporary_winner',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
